-- CREATE DATABASE `bms_demo`;
USE `bms_demo`;
# 用户表
CREATE TABLE `test_user` (
  `id` BIGINT UNSIGNED AUTO_INCREMENT NOT NULL COMMENT '自增ID',
  `username` VARCHAR(32) NOT NULL DEFAULT '' COMMENT '用户名',
  `password` VARCHAR(128) NOT NULL DEFAULT '' COMMENT '密码',
  `status` TINYINT UNSIGNED NOT NULL DEFAULT '0' COMMENT '状态',
  PRIMARY KEY (`id`)
) ENGINE=InnoDB CHARSET=utf8mb4 COMMENT='用户表';
# 用户角色关系表
CREATE TABLE `test_user_role` (
  `id` BIGINT UNSIGNED AUTO_INCREMENT NOT NULL COMMENT '自增ID',
  `user_id` BIGINT UNSIGNED NOT NULL DEFAULT '0' COMMENT '用户ID',
  `role_id` BIGINT UNSIGNED NOT NULL DEFAULT '0' COMMENT '角色ID',
  PRIMARY KEY (`id`)
) ENGINE=InnoDB CHARSET=utf8mb4 COMMENT='用户角色关系表';
# 角色表
CREATE TABLE `test_role` (
  `id` BIGINT UNSIGNED AUTO_INCREMENT NOT NULL COMMENT '自增ID',
  `role` VARCHAR(32) NOT NULL DEFAULT '' COMMENT '角色名',
  `description` VARCHAR(32) NOT NULL DEFAULT '' COMMENT '描述',
  PRIMARY KEY (`id`)
) ENGINE=InnoDB CHARSET=utf8mb4 COMMENT='角色表';
